#Requires AutoHotkey v2.0

global AutoPresetsText := Map(
    "SectionTitle", "自动识别配置",
    "Enable", "启用自动识别",
    "RecognizeDurationPrefix", "识别时间",
    "RecognizeDurationSuffix", "秒",
    "PresetList", "配置列表",
    "SkillIconList", "角色列表（双击重命名）",
    "RenameSkillIconTitle", "重命名",
    "RenameSkillIconPrompt", "请输入名称",
    "ExtraHotkey", "冒险团玩法信息",
    "MatchStrict", "严格标准",
    "CurrentPreset", "当前配置",
    "CaptureReference", "截取",
    "DeleteReference", "删除",
    "PickSkillRegion", "技能识别区域",
    "PickChatRegion", "聊天识别区域",
    "ChatReference", "聊天参考图",
    "CaptureChat", "截取",
    "DeleteChat", "删除",
    "ResetRegionConfirmTitle", "重新设置识别区域",
    "ResetRegionConfirm", "多分辨率无需重新设置识别区域，直接重新截图即可。`n`n调整识别区域会导致之前截的图全部失效。",
    "ResetRegionConfirmAction", "重新设置识别区域",
    "Cancel", "取消",
    "ResolutionList", "分辨率列表",
    "CaptureResolution", "截取分辨率",
    "DeleteResolution", "删除分辨率",
    "Save", "保存",
    "Recognizing", "正在识别角色",
    "HelpTitle", "自动识别说明",
    "Help", "连发运行且已开启时，按 Esc 或「冒险团玩法信息」绑定键后，按设定的识别时间每 500ms 识别一次技能图并切换配置，右下角提示正在识别角色；期间再按会重新计时。平时不识别。`n`n「自动识别」就是按技能栏切角色配置。「严格标准」100% 是已经放过容差、并按邻近/跨分辨率缩放的那套；0% 再为客户端缩小额外放宽，更容易认到也更容易误判。中间值在两套之间。`n`n一键连招勾选「屏蔽原键」时：请先打开游戏聊天框，框选「聊天识别区域」并截取参考图（尽量框边框或固定文字，避开闪烁光标）。连发运行期间搜到该图才放行原键，方便打字；搜不到则继续屏蔽。未截聊天图时屏蔽原键保持始终生效。`n`n流程：先点「截取分辨率」登记当前客户区尺寸。选择分辨率后，聊天参考图和角色列表都切换到该尺寸下的配置。截取或删除聊天图、技能图不会改分辨率列表。点击截取会为当前配置和所选分辨率新增一张技能图。匹配到对应配置才切换，技能识别失败不切换。",
    "RegionPickHint", "Enter确认，Esc取消"
)
