#Requires AutoHotkey v2.0

global exText := Map(
    "CommonSave", "保存",
    "CommonSaveToAll", "保存到所有配置",
    "DuplicateKey", "请勿重复添加按键",
    "PressKeyPrompt", "输入按键..",
    "LvRenListTitle", "已添加技能键",
    "LvRenShotTitle", "流星按键",
    "LvRenAdd", "添加",
    "LvRenDelete", "删除",
    "LvRenTitle", "旅人自动流星",
    "LvRenPageTitle", "旅人自动流星设置",
    "LvRenHelpTitle", "如何使用旅人自动流星",
    "LvRenHelp", "1、添加你想要发射流星的技能键`n2、设置游戏中流星的发射键（默认为Z）`n3、保存配置，启动连发并使用`n`nPS：建议和连发功能一起打开，效果更好",
    "GuanYuListTitle", "已添加技能键",
    "GuanYuShotTitle", "猛攻按键",
    "GuanYuAdd", "添加",
    "GuanYuDelete", "删除",
    "GuanYuDelayTitle", "延迟(ms)",
    "GuanYuTitle", "关羽自动猛攻",
    "GuanYuPageTitle", "关羽自动猛攻设置",
    "GuanYuHelpTitle", "如何使用关羽自动猛攻",
    "GuanYuHelp", "1、添加触发猛攻的技能键`n2、设置游戏中猛攻的发射键（默认Space）`n3、可手动设置猛攻出手延迟(ms，默认300)`n4、保存配置，启动连发并使用",
    "PetSkillListTitle", "已添加触发键",
    "PetSkillShotTitle", "触发按键",
    "PetSkillAdd", "添加",
    "PetSkillDelete", "删除",
    "PetSkillTitle", "自动宠物",
    "PetSkillPageTitle", "自动宠物设置",
    "PetSkillHelpTitle", "如何使用自动宠物",
    "PetSkillHelp", "1、添加你想触发宠物技能时按下的技能键`n2、设置游戏中的宠物技能键`n3、保存配置，启动连发并使用",
    "ZhanFaListTitle", "已添加技能键",
    "ZhanFaShotTitle", "炫纹按键",
    "ZhanFaBigShotTitle", "大炫纹键",
    "ZhanFaAdd", "添加",
    "ZhanFaDelete", "删除",
    "ZhanFaTitle", "战法自动炫纹",
    "ZhanFaPageTitle", "战法自动炫纹设置",
    "ZhanFaHelpTitle", "如何使用战法自动炫纹",
    "ZhanFaHelp", "    你的数据很差，我现在玩战法每130s只要能射出300次炫纹，每次差不多34824％的等效百分比，就能有相当于10447200％的输出水平，换算过来狠狠地超越了精灵骑士的三觉数据。虽然我作为爆发职业没有一个技能超过3000000％，作为续航职业没有一个技能秒伤能超过90000％，但是我的炫纹已经超越了地下城绝大多数职业(包括你)的水平，这便是战斗法师给我的骄傲的资本。",
    "ZhanFaHelpExtraTitle", "战斗法师の骄傲",
    "ZhanFaHelpExtra", "1、添加会触发炫纹/大炫纹的左边技能键`n2、设置游戏中的炫纹发射键（默认 Space）`n3、可选设置大炫纹发射键；它和炫纹共用同一批触发键，但每次按下只触发一次，不会连发`n4、保存配置，启动连发并使用",
    "JianZongDelay", "延迟时间(ms)",
    "JianZongSkillKey", "帝国剑术快捷键",
    "JianZongTitle", "帝国剑术延迟",
    "JianZongPageTitle", "帝国剑术延迟设置",
    "JianZongHelpTitle", "如何使用帝国剑术延迟",
    "JianZongHelp", "1、设置游戏中帝国剑术的技能按键`n2、设置帝国剑术第一刀后的延迟时间，单位毫秒`n3、保存配置，启动连发并使用`n`nPS：该按键不能打开连发，否则功能失效",
    "XiuLuoTitle", "修罗自动一觉",
    "XiuLuoPageTitle", "修罗自动一觉设置",
    "XiuLuoHelpTitle", "如何使用修罗自动一觉",
    "XiuLuoTriggerKey", "触发键",
    "XiuLuoXKey", "平X键",
    "XiuLuoWaveKey1", "波动剑1",
    "XiuLuoWaveKey2", "波动剑2",
    "XiuLuoWaveKey3", "波动剑3",
    "XiuLuoHelp", "1、设置一个触发键、一个平X键，以及三个波动剑键。`n2、启动连发后，在 DNF 窗口内按住触发键，会同时触发四个键的连发。`n3、平X键沿用全局连发间隔，三个波动剑键按全局连发间隔的三倍发送。`n4、如果触发键本身也开了主连发，启用本功能时会自动跳过该触发键的主连发，避免冲突。",
    "AutoRunLeftKey", "左方向键",
    "AutoRunRightKey", "右方向键",
    "AutoRunDelay", "延迟(ms)",
    "AutoRunPauseHotkey", "暂停快捷键",
    "AutoRunTitle", "自动奔跑设置",
    "AutoRunPageTitle", "自动奔跑设置",
    "AutoRunHelpTitle", "自动奔跑说明",
    "AutoRunHelp", "设置自动奔跑要监听的左右键，以及按住方向键后补发双击的延迟（毫秒）。`n默认 30ms；范围 1～400ms。`n如果游戏里方向键不是 Left/Right，请改成你的实际按键后保存。`n可设置独立暂停快捷键：在 DNF 窗口内按一次暂停自动奔跑，再按一次恢复；留空表示不使用。`n软件设置中的全局暂停快捷键仍会暂停全部模拟输入。",
    "ComboTitleLine", "一键连招设置",
    "ComboProfileList", "连招方案",
    "ComboAddProfile", "新建方案",
    "ComboRemoveProfile", "删除方案",
    "ComboImportProfiles", "导入",
    "ComboExportProfiles", "导出",
    "ComboSkillList", "连招技能 (双击可修改)",
    "ComboAddSkill", "添加技能",
    "ComboDeleteSkill", "删除技能",
    "ComboTriggerKey", "触发键",
    "ComboLoopMode", "循环",
    "ComboBlockOriginal", "屏蔽原键",
    "ComboApply", "应用方案",
    "ComboSaveClose", "保存",
    "ComboEditSkillKey", "技能键",
    "ComboEditDelay", "间隔(ms)",
    "ComboEditHold", "按下(ms)",
    "ComboEditOk", "确定",
    "ComboEditCancel", "取消",
    "ComboEmptySkillDisplay", "（空）",
    "ComboAddSkillEscTip", "输入按键..",
    "ComboTitle", "一键连招设置",
    "ComboHelpTitle", "一键连招说明",
    "ComboHelp", "在 DNF 窗口内按住「触发按钮」后，按顺序发送技能键。`n可配置多套方案；未设置触发键、触发键无效或没有有效技能的方案会在运行时跳过。`n勾选「循环」时，整套打完后若仍按住触发按钮会重新开始。`n勾选「屏蔽原键」后，触发键自身不会透传给游戏。若要打字，请在自动识别里框选聊天框并截取参考图：搜到聊天框时暂时放行原键，关掉聊天后恢复屏蔽。`n双击技能进入编辑对话框后清空按键，会作为「空技能」保留，仅按其延迟占位，不发送按键。",
    "ComboUnsetTrigger", "（未设置）",
    "ComboSkillCountSuffix", " 个技能",
    "ComboImportTitle", "导入连招方案",
    "ComboExportTitle", "导出连招方案",
    "ComboImportSuccessPrefix", "已导入 ",
    "ComboImportSuccessSuffix", " 套连招方案。",
    "ComboImportMissingSection", "不是有效的一键连招导出文件。",
    "ComboImportNoValidProfiles", "导出文件中没有可导入的连招方案。",
    "ComboImportMissingFile", "导入文件不存在。",
    "ComboImportFailed", "导入连招方案失败。",
    "ComboExportSuccess", "连招方案已导出。",
    "ComboExportFailed", "导出连招方案失败。",
    "ComboEditTitle", "编辑连招技能",
    "MultiKeyTitleLine", "多键并发设置",
    "MultiKeyProfileList", "主键绑定",
    "MultiKeyAddProfile", "新建主键",
    "MultiKeyRemoveProfile", "删除主键",
    "MultiKeyKeyList", "并发按键",
    "MultiKeyFirstKey", "首按键",
    "MultiKeyAddKey", "添加按键",
    "MultiKeyDeleteKey", "删除按键",
    "MultiKeySaveClose", "保存",
    "MultiKeyTitle", "多键并发设置",
    "MultiKeyHelpTitle", "多键并发说明",
    "MultiKeyHelp", "在 DNF 窗口内按住「主键」时，会按全局连发间隔同时补发该主键绑定的并发按键，效果接近主连发开启后同时按住这些键。`n主键原键始终屏蔽，不会进游戏；若要打出主键本身，把它加进并发按键即可。`n若设置了「首按键」，按住主键瞬间先发出首按键，过全局连发间隔后整组并发按键（含首按键）按全局间隔一起补发；并发按键与首按键的间隔、按下保持均跟随全局设置。`n按住主键时屏蔽原键，绑定的并发按键按主连发同一套逐键定时补发，效果接近你同时按住这些键。绑定按当前配置分别保存，自动识别切到另一套配置时要用那套自己的多键并发。`n左侧可绑定多组主键；未设置主键的组会在运行时跳过。`n同一主键不能重复添加。",
    "MultiKeyUnsetTrigger", "（未设置）",
    "MultiKeyKeyCountSuffix", " 个按键"
)
