#Requires AutoHotkey v2.0

global MainText := Map(
    "AppTitle", "DAF连发工具 - DNF AutoFire",
    "AppTitleWithVersion", "DAF连发工具 - DNF AutoFire - v",
    "TraySettings", "连发设置",
    "TrayExit", "退出连发",
    "TrayTip", "DAF连发工具",
    "VersionPrefix", "版本信息: v",
    "ClearKeys", "清空",
    "KeySection", "按键设置 - [ 灰色=关闭 蓝色=启用 角标=独立参数 (右键可设置间隔/延迟) ]",
    "PresetSection", "配置设置 - [ 单击切换，右键配置管理 ]",
    "CurrentPreset", "当前配置名称:",
    "AutoFireInterval", "全局连发间隔(ms)",
    "QuickSwitchHotkey", "快速切换热键",
    "Setting", "软件设置",
    "AutoPresets", "自动识别",
    "LongZhan", "龙战识别",
    "Start", "启动连发",
    "FeatureSection", "其他功能",
    "LvRen", "旅人自动流星",
    "GuanYu", "关羽自动猛攻",
    "JianZong", "帝国剑术延迟",
    "ZhanFa", "战法自动炫纹",
    "PetSkill", "自动宠物",
    "XiuLuo", "修罗自动一觉",
    "AutoRun", "自动奔跑",
    "Combo", "一键连招",
    "MultiKey", "多键并发",
    "NewPreset", "新建配置",
    "RenamePreset", "重命名",
    "ClonePreset", "克隆配置",
    "DeletePreset", "删除配置",
    "PresetNameInvalidChar", "配置名称不能包含 | 字符",
    "PresetNameRequired", "请输入配置名称",
    "PresetNameExists", "配置名称已存在",
    "ClonePresetPrompt", "请输入新配置名称",
    "ClonePresetSuffix", "-克隆",
    "NewPresetPrompt", "请输入新配置名称",
    "NewPresetDefault", "新配置",
    "RenamePresetTitle", "重命名配置",
    "RenamePresetPrompt", "请输入新的配置名称",
    "SelectValidPreset", "请选择有效的配置",
    "KeepOnePreset", "至少保留一个配置",
    "DeletePresetConfirmPrefix", "确定删除配置：",
    "DeletePresetConfirmSuffix", "？",
    "IntegerMsRequired", "请输入整数毫秒。",
    "IntegerMsPositive", "请输入 1 或更大的整数毫秒。",
    "IntegerMsNonNegative", "请输入 0 或更大的整数毫秒。",
    "KeyParamsTitlePrefix", "独立连发参数 - ",
    "KeyParamsIntervalLabel", "连发间隔",
    "KeyParamsDelayLabel", "按键延迟",
    "KeyParamsFormatRequired", "连发间隔和按键延迟都必须填写整数毫秒。",
    "KeyParamsAlreadyDefault", "该键未设置独立参数，已在使用全局间隔和默认 8ms 延迟。",
    "SetKeyParams", "设置独立连发参数…",
    "UseDefaultParams", "恢复默认连发参数",
    "Ok", "确定",
    "Cancel", "取消",
    "SettingTabGeneral", "通用设置",
    "SettingTabHelp", "帮助说明",
    "SettingTabAbout", "关于",
    "SettingAutoStart", "软件打开后自动启动连发",
    "SettingOnSystemStart", "开机后自动启动",
    "SettingBlockWin", "游戏内屏蔽Win键",
    "SettingSubprocessErrorLog", "子进程异常错误日志",
    "SettingCloseToTray", "关闭按钮最小化到托盘",
    "SettingGlobalPauseHotkey", "全局暂停快捷键",
    "GlobalPauseOn", "连发已暂停",
    "GlobalPauseOff", "连发已恢复",
    "Save", "保存",
    "SettingHelp", "如何使用DAF连发工具`n`n1、点击窗口中的键盘，将想启动连发的键位变成蓝色色`n2、在左侧列表单击切换配置，需要时可新建空配置、重命名或克隆当前配置`n3、点击启动连发，即可使用`n4、右侧可打开自动识别、龙战识别和其他职业功能；自动识别可调严格标准，多键并发可设首按键`n`nPS：主界面改动会在切换配置、启动连发或关闭主窗口前自动保存到当前配置。扩展功能窗口点击保存、按ESC或点右上角关闭时，也会自动保存当前修改。游戏中也可以打开快速切换窗口，使用上下键和回车可以快速切换配置，记得设置快捷键哦`n默认快捷键 Alt + `` （键盘1左边，Tab上边的那个）",
    "CurrentMaintainedPost", "当前版本维护地址：",
    "CurrentMaintainedPostUrl", "https://bbs.colg.cn/thread-9593722-1-1.html",
    "Source", "源码：",
    "SourceUrl", "https://github.com/mouyase/DNFAutoFire",
    "OriginalPost", "原帖地址：",
    "OriginalPostUrl", "https://bbs.colg.cn/thread-8894989-1-1.html",
    "StartupShortcutName", "DNFAutoFire.lnk",
    "QuickSwitchHint", "使用键盘上下键选择配置，按空格或回车快速切换，按ESC关闭窗口",
    "QuickSwitchStart", "切换并启动连发",
    "QuickSwitchStop", "停止连发",
    "QuickSwitchTitle", "快速切换"
)
